config/routes.rb
# == Route Map
#
#               Prefix Verb   URI Pattern                      Controller#Action
#                 root GET    /                                pages#home
#                login GET    /login(.:format)                 session#new
#                      POST   /login(.:format)                 session#create
#                      DELETE /login(.:format)                 session#destroy
#        complete_feat GET    /feats/complete/:id(.:format)    feats#complete
# show_completed_feats GET    /feats/completed(.:format)       feats#show_completed
#          clear_feats GET    /feats/completed/clear(.:format) feats#clear_feats
#               admins GET    /admin(.:format)                 admins#index
#                users GET    /users(.:format)                 users#index
#                      POST   /users(.:format)                 users#create
#             new_user GET    /users/new(.:format)             users#new
#            edit_user GET    /users/:id/edit(.:format)        users#edit
#                 user GET    /users/:id(.:format)             users#show
#                      PATCH  /users/:id(.:format)             users#update
#                      PUT    /users/:id(.:format)             users#update
#                      DELETE /users/:id(.:format)             users#destroy
#                feats GET    /feats(.:format)                 feats#index
#                      POST   /feats(.:format)                 feats#create
#             new_feat GET    /feats/new(.:format)             feats#new
#            edit_feat GET    /feats/:id/edit(.:format)        feats#edit
#                 feat GET    /feats/:id(.:format)             feats#show
#                      PATCH  /feats/:id(.:format)             feats#update
#                      PUT    /feats/:id(.:format)             feats#update
#                      DELETE /feats/:id(.:format)             feats#destroy
#               badges GET    /badges(.:format)                badges#index
#                      POST   /badges(.:format)                badges#create
#            new_badge GET    /badges/new(.:format)            badges#new
#           edit_badge GET    /badges/:id/edit(.:format)       badges#edit
#                badge GET    /badges/:id(.:format)            badges#show
#                      PATCH  /badges/:id(.:format)            badges#update
#                      PUT    /badges/:id(.:format)            badges#update
#                      DELETE /badges/:id(.:format)            badges#destroy
#

Rails.application.routes.draw do

  root to: 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/dashboard/badges' => 'dashboard#badges', as: 'dashboard_badges'


  get '/feats/complete/:id' => 'feats#complete', as: 'complete_feat'
  get '/feats/completed' => 'feats#show_completed', as: 'show_completed_feats'
  get '/feats/completed/clear' => 'feats#clear_feats', as: "clear_feats"


  get '/admin' => 'admins#index', as: 'admins'



  resources :users
  resources :feats
  resources :badges


  
end

app/models/feat.rb
# == Schema Information
#
# Table name: feats
#
#  id          :integer          not null, primary key
#  description :text
#  deadline    :date
#  completed   :boolean
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Feat < ActiveRecord::Base
	belongs_to :user 

	validates :description, presence: true, length: {maximum: 64}
	
end 

app/controllers/feats_controller.rb
class FeatsController < ApplicationController 
	layout 'dashboard'

	before_action :check_level, :check_badges

	def index 
		redirect_to root_path unless @current_user
		@uncomplete = @current_user.feats.where(completed: false).order(deadline: :asc)
	end 

	def new
		redirect_to root_path unless @current_user
		@feat = Feat.new
	end 

	def create
		@feat = Feat.new feat_params
		@feat.completed = false
		@feat.user = @current_user
		if @feat.save
			redirect_to feats_path
		else 
			render :new
		end
	end 

	def complete
		@feat = Feat.find params[:id]
		@feat.completed = true
		@feat.save
		redirect_to feats_path
		@current_user.xp += 10
		@current_user.save
	end 

	def show_completed
		@completed_feats = @current_user.feats.where(completed: true)
	end 

	def clear_feats
		completed = @current_user.feats.where(completed:true)
		completed.destroy_all
		redirect_to show_completed_feats_path
	end 

	private
	def feat_params
		params.require(:feat).permit(:description, :deadline)
	end 

	def check_level
		@current_user.update_level 	if logged_in?
	end 

	def check_badges
		all_badges = Badge.all 
		@badge_msg = []
		all_badges.each do |b|
			unless @current_user.badges.include? b
				@current_user.badges << b and @badge_msg << "Congrats! You got the '#{b.name}' badge!" if b.conditions_met?(@current_user) 
				
			end 
		end 
		@badge_msg
	end 

end 

app/views/feats/index.html.erb
<div class="row">
	<div class="small-12 columns">
		<!-- 9 feats -->
		<h1 id="feats-number">
			<span><%= @uncomplete.count %></span> feats
		</h1>
	</div>
</div>
<div class="row">
	<div class="large-9 medium-9 small-6 columns">
		<!-- Badges -->
		<% @current_user.badges.each do |b| %>
			<div class="badge-icon">
				<%= link_to (image_tag b.image), dashboard_badges_path %>
			</div>
		<% end  %>
	</div>
	<div class="large-3 medium-3 small-6 text-right columns">
		<!-- Add Feat -->
		<%= button_to '+ ADD FEAT', new_feat_path, method: :get, class: 'button' %>
	</div>
</div>
<% if @uncomplete.empty? %>
	<div data-alert class="alert-box warning">
 		You haven't created any feats, why don't you try adding one?
			<a href="#" class="close">&times;</a>
	</div>
<% end %>
<div class="row tasks-row">
	<div class="small-11 columns small-centered tasks-container">
		<!-- Tasks -->	
		<% @uncomplete.each do |f| %>
			<div class="row task-row">
				<div class="small-2 columns">
					<%= link_to (image_tag 'tick.svg'), complete_feat_path(f) %>
				</div>
				<div class="small-5 large-6 columns"><p><%= f.description %></p></div>
				<div class="small-5 large-4 columns text-right"><p><span class="<%= "ago" if f.deadline && f.deadline < Time.now  %> "><%= time_ago_in_words f.deadline if f.deadline %> <%= "ago" if f.deadline && f.deadline < Time.now  %></span></p></div>
			</div>
		<% end %>
	</div>
</div>

app/views/feats/new.html.erb
<h1 class="text-center add-text">Add a feat</h1>

<div class="row">
	<div class="small-9 columns small-centered">
		<div class="panel">
		<% if @feat.errors.any? %>
			<% @feat.errors.full_messages.each do |e| %>
				<div data-alert class="alert-box alert">
		      <%= e %>
		    	<a href="#" class="close">&times;</a>
				</div>
			<% end %>
		<% end %>

		<%= form_for @feat do |f| %>
			<div class="input-group">
				<%= f.label :description %>
				<%= f.text_field :description, autofocus: true %>
			</div>
			<div class="input-group">
				<%= f.label :deadline %>
				<%= f.date_field :deadline %>
			</div>
			<div class="input-group">
				<%= f.submit class: 'button expand'%>
			</div>

		<% end %>
		
	</div>

</div>

app/views/feats/show_completed.html.erb
<div class="row">
	<div class="small-12 columns">
		<!-- 9 feats -->
		<h1 id="feats-number-completed">
			<span><%= @completed_feats.count %></span> feats completed
		</h1>
	</div>
</div>
<div class="row">
	<div class="large-9 medium-9 small-6 columns">
		<!-- Badges -->
		<% @current_user.badges.each do |b| %>
			<div class="badge-icon">
				<%= link_to (image_tag b.image), dashboard_badges_path %>
			</div>
		<% end  %>
	</div>
	<div class="large-3 medium-3 small-6 text-right columns">
		<!-- Add Feat -->
		<%= button_to '- CLEAR ALL', clear_feats_path, method: :get, class: 'button' %>
	</div>
</div>
<div class="row tasks-row">
	<div class="small-11 columns small-centered tasks-container">
		<!-- Tasks -->	

		<% @completed_feats.each do |f| %>
			<div class="row task-row">
				<div class="small-2 columns">
					<%= image_tag 'tick-complete.svg' %>
				</div>
				<div class="small-5 large-6 columns"><p><%= f.description %></p></div>
				<div class="small-5 large-4 columns text-right"><p><span class="<%= "ago" if f.deadline && f.deadline < Time.now  %> "><%= time_ago_in_words f.deadline if f.deadline %> <%= "ago" if f.deadline && f.deadline < Time.now  %></span></p></div>
			</div>
		<% end %>
	</div>
</div>