config/routes.rb
# == Route Map
#
#               Prefix Verb   URI Pattern                      Controller#Action
#                 root GET    /                                pages#home
#                login GET    /login(.:format)                 session#new
#                      POST   /login(.:format)                 session#create
#                      DELETE /login(.:format)                 session#destroy
#        complete_feat GET    /feats/complete/:id(.:format)    feats#complete
# show_completed_feats GET    /feats/completed(.:format)       feats#show_completed
#          clear_feats GET    /feats/completed/clear(.:format) feats#clear_feats
#               admins GET    /admin(.:format)                 admins#index
#                users GET    /users(.:format)                 users#index
#                      POST   /users(.:format)                 users#create
#             new_user GET    /users/new(.:format)             users#new
#            edit_user GET    /users/:id/edit(.:format)        users#edit
#                 user GET    /users/:id(.:format)             users#show
#                      PATCH  /users/:id(.:format)             users#update
#                      PUT    /users/:id(.:format)             users#update
#                      DELETE /users/:id(.:format)             users#destroy
#                feats GET    /feats(.:format)                 feats#index
#                      POST   /feats(.:format)                 feats#create
#             new_feat GET    /feats/new(.:format)             feats#new
#            edit_feat GET    /feats/:id/edit(.:format)        feats#edit
#                 feat GET    /feats/:id(.:format)             feats#show
#                      PATCH  /feats/:id(.:format)             feats#update
#                      PUT    /feats/:id(.:format)             feats#update
#                      DELETE /feats/:id(.:format)             feats#destroy
#               badges GET    /badges(.:format)                badges#index
#                      POST   /badges(.:format)                badges#create
#            new_badge GET    /badges/new(.:format)            badges#new
#           edit_badge GET    /badges/:id/edit(.:format)       badges#edit
#                badge GET    /badges/:id(.:format)            badges#show
#                      PATCH  /badges/:id(.:format)            badges#update
#                      PUT    /badges/:id(.:format)            badges#update
#                      DELETE /badges/:id(.:format)            badges#destroy
#

Rails.application.routes.draw do

  root to: 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/dashboard/badges' => 'dashboard#badges', as: 'dashboard_badges'


  get '/feats/complete/:id' => 'feats#complete', as: 'complete_feat'
  get '/feats/completed' => 'feats#show_completed', as: 'show_completed_feats'
  get '/feats/completed/clear' => 'feats#clear_feats', as: "clear_feats"


  get '/admin' => 'admins#index', as: 'admins'



  resources :users
  resources :feats
  resources :badges


  
end

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'feats', root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
    	<% if @current_user %>

      	<li><%= link_to @current_user.username + "'s Dashboard", feats_path %></li>
      	<li><%= link_to 'Logout', login_path, :method => :delete %></li>
      <% else %>
       	<li><%= link_to 'Login', login_path %></li> 
        <li><%= link_to 'Register', new_user_path %></li>   
      <% end %>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">

    </ul>
  </section>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Feats" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!-- Main Navigation -->
    <%= render 'layouts/navigation' %>
    
    <div class="admin-area">
      <div class="row">
        <h1 class="admin-title">Admin Area</h1>
        <!-- Side Bar -->
        <div class="columns large-4 admin-side">
          <ul class="side-nav">
            <li><%= link_to 'List Badges', badges_path %></li>
            <li><%= link_to 'Add Badge', new_badge_path %></li>
          </ul>
        </div>
        <!-- Content -->
        <div class="columns large-8">
          <%= yield %>
        </div>
      </div>
     </div>    
    </div>

     

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Feats" %></title>

    <%= stylesheet_link_tag    "application" %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!-- Navigation -->
    <%= render 'layouts/navigation' %>

    <!-- Content -->
    <div class="dashboard-row">
      <div class="dashboard-container">
        <!-- Sidebar -->
        <div class="medium-3 columns sidebar" id="sidebar">
        
          <!-- Profile Section -->
          <div class="row profile">
            <div class="small-12 columns text-centered">
              <div class="row theme-background-<%= @current_user.theme_option %>">
                <% if @current_user.avatar.exists? %>
                  <div class="profile-avatar text-center">
                  <%= image_tag @current_user.avatar.url(:square) %>             </div>
                <% else %>
                  <div class="profile-picture"></div>
                <% end %>
              </div>
              <div class="row theme-background-<%= @current_user.theme_option %>">
                <div class="row white text-center" id="user-specs">
                  <div class="small-4 columns">
                    <h4 class="white"><%= @current_user.feats.where(completed: false).count  %></h4>
                    <p>feats</p>
                  </div>
                  <div class="small-4 columns">
                   <h4 class="white"><%= @current_user.feats.where(completed: true).count %></h4>
                    <p>competed</p>
                  </div>
                  <div class="small-4 columns">
                    <h4 class="white"><%= @current_user.badges.count %></h4>
                    <p>badges</p>
                  </div>
                </div>
              </div>
              <div class="row theme-background-<%= @current_user.theme_option %> progress-meter">
                <div class="progress small-10 small-centered columns round ">
                  <span class="meter" style="width: <%= @current_user.xp_to_percent %> "></span>
                </div>
              </div>
              <div class="row theme-background-<%= @current_user.theme_option %>">
                <div class="small-12 small-centered columns"><p class="text-center"><strong>LVL <%= @current_user.level %></strong></p></div>
              </div>           
            </div>
          </div>
          <!-- Nav section -->
          <div class="row side-bar-nav">
          <div class="large-12 columns">
            <ul class="side-nav text-right side-nav-custom">
              <li class=<%= 'active' if current_page?(:controller => 'feats', :action => 'index') %>>
                <%= link_to icon('tachometer') + "DASHBOARD", feats_path %>
              </li>
              <li class=<%= 'active' if current_page?(:controller => 'feats', :action => 'show_completed') %>>
              <%= link_to icon('check-square') + 'COMPLETED', show_completed_feats_path %></li>
              <li class=<%= 'active' if current_page?(:controller => 'dashboard', :action => 'badges') %>><%= link_to icon('trophy') +  'BADGES', dashboard_badges_path %></li>
              <li><%= link_to icon('bolt') + 'ADMIN PANEL', admins_path if is_admin? %></li>

              <li><%= link_to icon('cog') + 'SETTINGS', edit_user_path(@current_user)%></li>
            </ul>
          </div>
          </div>

          
        </div>
        <!-- Main Content -->
        <div class="medium-9 columns dashboard-main">
          <% unless @badge_msg.empty? %>
            <div class="row top-msg">
              <div class="columns small-12">
                <% @badge_msg.each do |b| %>
                  <div data-alert class="alert-box">
                    <%= b %>
                    <a href="#" class="close">&times;</a>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>





    <%= javascript_include_tag "application" %>
  </body>


</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Feats" %></title>

    <%= stylesheet_link_tag    "application" %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body id="pagebody">
    <!-- Navigation -->
    <%= render 'layouts/navigation' %>

    <!-- Content -->
    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>